version: "3"

services:

  en_splitviewer_server:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile-server
    ports:
      - 80
    networks:
      - default
      - webproxy
    volumes:
      - ../images:/app/server/img
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=en.api.splitviewer.com
      - LETSENCRYPT_HOST=en.api.splitviewer.com
      - LETSENCRYPT_EMAIL=ermineaweb@gmail.com
    depends_on:
      - en_splitviewer_db

  en_splitviewer_client:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile-client
    networks:
      - default
      - webproxy
    ports:
      - 80
    env_file:
      - ../.env
    environment:
      - VIRTUAL_HOST=en.splitviewer.com
      - LETSENCRYPT_HOST=en.splitviewer.com
      - LETSENCRYPT_EMAIL=ermineaweb@gmail.com
    depends_on:
      - en_splitviewer_server

  en_splitviewer_db:
    image: mongo
    user: 2000:2000
    networks:
      - default
    command: --quiet --logpath /dev/null
    user: 1000:1000
    volumes:
      - db:/data/db

volumes:
  db:
    
networks:
  webproxy:
    external:
      name: webproxy
  
  default:
