FROM node:14-slim as build-stage
WORKDIR /app
COPY ./client/package*.json ./
RUN npm install --silent
COPY ./client/ ./
RUN npm run build

FROM nginx:stable-alpine
COPY ./deploy/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/build/ /usr/share/nginx/html/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]